apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  generation: 1
  labels:
    app: reactapp
  name: reactapp
  namespace: sprike201801222
spec: {}
